-- Config/ProfileTemplate.lua
-- Template utilisé lors de la création d'un nouveau profil vierge.
-- Généré depuis un profil de référence via le code d'export de l'addon.
-- P.Create() fait DeepCopy(ns.ProfileTemplate) puis MergeDefaults(…, ns.Defaults)
-- pour combler toute clé absente ajoutée ultérieurement.
local addonName, ns = ...

ns.ProfileTemplate = {
  resourceCircle = {
    textColor = {0, 0.6901960784, 1, 1},
    fontSize = 20,
    overlayRatio = 0.5,
    staggerArcRatio = 0.5,
    glowSize = 1,
    staggerOverlayRatio = 0.5,
    secResFont = "Interface\\AddOns\\SharedMedia_MyMedia\\font\\PTSansNarrow-Bold.ttf",
    arcSizeRatio = 1,
    glowEnabled = false,
    dotPositions = {{-19,8},{-11,3},{0,0},{11,3},{19,8}},
    bgSize = 88,
    secResTextSize = 16,
    anchor = "CENTER",
    dotColors = {{0.8,0,0.8},{1,0.2,0.8},{1,0.2,0.6},{1,0.2,0.8},{0.8,0,0.8}},
    visibilityMode = "combat",
    size = 85,
    enabled = true,
    dotSizes = {3,5,9,5,3},
    font = "Interface\\AddOns\\SharedMedia_MyMedia\\font\\PTSansNarrow-Bold.ttf",
    arcSize = 64,
    secondaryDotsSpread = 30,
    arcOffsetY = 5,
    secondaryDotsRadius = 0.7,
    secondaryDotsRotation = 180,
    y = 0,
    x = 0,
    secondaryDotsSize = 0.25,
    secResTextOffsetY = 0,
    secResTextOffsetX = 0,
    secondaryDotsReversed = false,
    glowOpacity = 0.85,
    arcOffsetX = 27,
  },
  healthCircle = {
    fontSize = 12,
    overlayRatio = 0.68,
    arcSizeRatio = 0.9,
    hideDelay = 2.5,
    anchor = "BOTTOMLEFT_OFFSET",
    anchorPctY = 0.28,
    visibilityMode = "always",
    size = 40,
    enabled = true,
    dotSizes = {0.4,3,7,3,0.4},
    anchorPctX = 0.22,
    arcOffsetY = 2,
    bgSize = 44,
    textColor = {0.3,0.9,0.3,1},
    arcSize = 32,
    font = "Interface\\AddOns\\SharedMedia_MyMedia\\font\\PTSansNarrow-Bold.ttf",
    dotColors = {{0.1,0.5,0.1},{0.2,0.7,0.2},{0.3,0.9,0.3},{0.2,0.7,0.2},{0.1,0.5,0.1}},
    dotPositions = {{-9,1},{-5,1},{0,0},{5,1},{9,1}},
    barColor = {0.2,0.9,0.2,1},
    y = 100,
    x = 200,
    arcOffsetX = 13,
  },
  spellEffects = {
    enabled = false,
    orbCombos = {},
    oocCombos = {},
    auraCombos = {},
    modelSize = 200,
    combos = {},
    combosAliases = {},  -- aliasSpellID → configuredSpellID
    spells = {},
  },
  topTargetBar = {
    ttBgW = 150,
    hpAnchor = "RIGHT",
    barOX = 0,
    ttNameOX = 0,
    ttBgH = 40,
    enabled = false,
    nameFont = "Interface\\AddOns\\SharedMedia_MyMedia\\font\\PTSansNarrow-Bold.ttf",
    bgOY = 0,
    showPowerBar = false,
    y = 0,
    x = 0,
    ttBarW = 150,
    ttBgOY = 0,
    bgOX = 0,
    showTargetOfTarget = false,
    ttNameOY = 0,
    ttBgOX = 0,
    hpOY = 0,
    nameOX = 0,
    ttBarOX = 0,
    ttBarH = 10,
    ttBarOY = -15,
    barH = 10,
    hpOX = 0,
    tty = -75,
    hpFont = "Interface\\AddOns\\SharedMedia_MyMedia\\font\\PTSansNarrow-Bold.ttf",
    bgW = 500,
    ttx = 0,
    hpFontSize = 12,
    nameOY = -10,
    bgH = 10,
    barOY = 0,
    barW = 500,
  },
  unitBars = {
    showDots = false,
    useTankHeight = false,
    reversed = true,
    bgColor = {0.0549,0.0549,0.0549,1},
    locked = false,
    hideOutOfCombat = false,
    visibilityMode = "always",
    enabled = true,
    nameFont = "Interface\\AddOns\\SharedMedia_MyMedia\\font\\PTSansNarrow-Bold.ttf",
    dotGap = 0,
    dotSize = 10,
    font = "Interface\\AddOns\\SharedMedia_MyMedia\\font\\PTSansNarrow-Bold.ttf",
    hpDisplayMode = "pct",
    tankHeight = 16,
    textSize = 12,
    bars = {
      player = {y=0, x=-250, fillColor={0.78,0.61,0.44,1}, enabled=true, height=20, nameOffX=0, nameOffY=2,  width=200},
      target = {y=0, x=250,  fillColor={0.72,0.59,0.39,1}, enabled=true, height=20, nameOffX=35, nameOffY=0, width=200},
      focus  = {y=0, x=500,  fillColor={0.71,0.6,0.49,1},  enabled=true, height=20, nameOffX=0, nameOffY=0,  width=200},
      pet    = {y=0, x=-500, fillColor={0.71,0.6,0.49,1},  enabled=true, height=20, nameOffX=0, nameOffY=0,  width=200},
      targettarget = {y=-30, x=250, fillColor={0.41,0.41,0.41,1}, enabled=true, height=10, nameOffX=0, nameOffY=0, width=100},
    },
    nameSize = 15,
    dotRatio = 0,
  },
  themes = {
    [262] = {resourceCircle = {dotColors={{1,0.3,0},{1,0.5,0.1},{1,0.6,0.2},{1,0.5,0.1},{1,0.3,0}}, textColor={1,0.4,0,1}}},
    [263] = {resourceCircle = {dotColors={{0.8,0,0.8},{1,0.2,0.8},{1,0.2,0.6},{1,0.2,0.8},{0.8,0,0.8}}, textColor={0,0.6901960784,1,1}}},
    [264] = {resourceCircle = {dotColors={{0.1,0.6,0.3},{0.2,0.8,0.4},{0.3,0.9,0.5},{0.2,0.8,0.4},{0.1,0.6,0.3}}, textColor={0.2,0.9,0.4,1}}},
  },
  outOfCombatResourceCircle = {
    fontSize = 9,
    glowOpacity = 1,
    arcSizeRatio = 1,
    glowEnabled = false,
    anchorPctY = 0.3606598674,
    visibilityMode = "always",
    size = 40,
    enabled = true,
    secondaryDotsReversed = false,
    anchorPctX = 0.3305468986,
    secondaryDotsRadius = 0.7,
    secondaryDotsRotation = 90,
    y = 0,
    font = "Interface\\AddOns\\SharedMedia_MyMedia\\font\\PTSansNarrow-Bold.ttf",
    secondaryDotsSize = 0.05,
    overlayRatio = 0.75,
    x = 0,
    secondaryDotsSpread = 5,
    glowSize = 1,
  },
  xpBar = {
    restIndicator = false,
    levelBg = {y=-6.5, x=-20, rot=175, w=87, h=54},
    restScale = 1,
    restY = 20,
    restX = 20,
    tooltipFrame = {bgRot=14, bgH=97, w=175, y=1.5, x=46, bgW=244, bgOffY=37, bgOffX=-100, h=48},
    enabled = true,
    repEnabled = false,
    companionXP = false,
    fontLevel = "Interface\\AddOns\\SharedMedia_MyMedia\\font\\PTSansNarrow-Bold.ttf",
    repDisplayMode = "tracked",
  },
  colors = {
    overrides = {},
    useClassDefaults = true,
  },
  minimapButton = {
    hidden = false,
    angle = 225,
  },
  castBar = {
    colorBySchool = false,
    timerJustify = "LEFT",
    timerOffY = 0,
    locked = false,
    nameOffX = 0,
    nameOffY = 0,
    enabled = false,
    nameSize = 15,
    timerSize = 12,
    timerFont = "Interface\\AddOns\\SharedMedia_MyMedia\\font\\PTSansNarrow-Bold.ttf",
    barColor = {0.471,0.392,0.271,1},
    width = 200,
    y = -400,
    x = 0,
    nameJustify = "CENTER",
    height = 15,
    font = "Interface\\AddOns\\SharedMedia_MyMedia\\font\\PTSansNarrow-Bold.ttf",
    timerOffX = 0,
  },
  rotationHelper = {
    y = -220,
    x = 0,
    enabled = false,
    anchor = "TOP",
    iconSize = 40,
  },
  priorityBar = {
    chargePosition = "CENTER",
    slotsBySpec = {},
    chargeColor = {1,1,1,1},
    chargeFontSize = 16,
    iconSize = 30,
    verticalOffset = 0,
    spellColors = {},
    borderSize = 1,
    desaturateOnCooldown = true,
    borderColor = {1,1,1,0.8999999762},
    showBorder = false,
    showCharges = false,
    visibilityMode = "always",
    showCooldownText = false,
    enabled = false,
    procStartIndex = 1,
    hideUnlearned = true,
    chargeOffsetX = 0,
    iconSpacing = 15,
    sideOffset = 50,
    cooldownFontSize = 16,
    showCooldownSwipe = true,
    glowColor = {1,0.85,0,0.8},
    loopGlowIndex = 1,
    borderStyle = "solid",
    glowType = "pulse",
    cooldownTextColor = {1,1,1,1},
    chargeOffsetY = 0,
    useSpecGlowColor = false,
    glowSize = 16,
  },
  skyriding = {
    mask2Size = 80,
    orbSize = 12,
    hidePriorityBar = false,
    hideRotationHelper = true,
    mask1Size = 100,
    orbSpacing = 18,
    colorGlow = {1,0.764705956,0,1},
    scale = 1,
    colorNoGlow = {0.9529412389,0.9529412389,1,1},
    speedSize = 120,
    textSize = 14,
    hideHealthCircle = false,
    enabled = false,
    dotOffsetY = -15,
    hideOOCResourceCircle = false,
    bgSize = 120,
    x = -250,
    colorMode = "custom",
    orbStartAngle = 0,
    dotSize = 5,
    y = 250,
    font = "Interface\\AddOns\\SharedMedia_MyMedia\\font\\PTSansNarrow-Bold.ttf",
    orbRadius = 60,
    hideUnitBars = false,
    hideAtLanding = false,
    hideResourceCircle = false,
    dotOffsetX = 0,
    ascentSize = 90,
  },
}
